import { Select as DSSelect } from '../../components/ui/DesignSystem';
import { Card as DSCard } from '../../components/ui/DesignSystem';
import { ButtonSecondary as DSButtonSecondary, Input as DSInput, Textarea as DSTextarea } from '../../components/ui/DesignSystem';
import ProjectImage from '../../components/shared/ProjectImage';
import ProjectImageField from '../../components/shared/ProjectImageField';
import { useModuleDraft } from '../useModuleDraft';
import { lazy, Suspense, useState } from 'react';
import { saveCourse, type Course, type CoursesData, type Lesson } from './model';
import type { ModuleProject } from '../moduleProjects';
import './courses.css';
const CourseRecorder = lazy(() => import('./CourseRecorder'));
export type CoursesProps = { data: CoursesData; onChange: (data: CoursesData) => void; project?: ModuleProject; userId?: string };
export default function CoursesEditor({data,onChange,project,userId}:CoursesProps){
  const [course,setCourse]=useState<Course|null>(null);
  const [moduleId,setModuleId]=useState('');const [lessonId,setLessonId]=useState('');
  const [message,setMessage]=useState('');const [recording,setRecording]=useState(false);
  useModuleDraft(!!course && JSON.stringify(course) !== JSON.stringify(data.courses.find(item => item.id === course.id)));
  const activeModule=course?.modules.find(module=>module.id===moduleId);
  const lesson=activeModule?.lessons.find(item=>item.id===lessonId);
  function updateLesson(patch:Partial<Lesson>){if(!course)return;setCourse({...course,modules:course.modules.map(module=>module.id===moduleId?{...module,lessons:module.lessons.map(item=>item.id===lessonId?{...item,...patch}:item)}:module)});}
  function choose(value:Course){if(course&&JSON.stringify(course)!==JSON.stringify(data.courses.find(item=>item.id===course.id))&&!window.confirm('¿Descartar la edición del curso actual?'))return;setCourse(structuredClone(value));setModuleId(value.modules[0]?.id??'');setLessonId(value.modules[0]?.lessons[0]?.id??'');setRecording(false);}
  function save(){if(!course)return;try{const next=saveCourse(data,course);onChange(next);setCourse(next.courses.find(item=>item.id===course.id)!);setMessage('Curso actualizado. Guarda los cambios del proyecto.');}catch(error){setMessage((error as Error).message);}}
  return <div className="courses-module"><h2>Creator Studio · Cursos</h2><p role="status">{message}</p>
    <DSCard as="section" className="component-card"><div className="component-header"><h3>Mis cursos</h3><DSButtonSecondary onClick={()=>choose({id:crypto.randomUUID(),name:'Nuevo curso',description:'',price:0,cover:'',modules:[]})}>Nuevo curso</DSButtonSecondary></div><div className="courses-actions">{data.courses.map(item=><DSButtonSecondary key={item.id} onClick={()=>choose(item)}>{item.name}</DSButtonSecondary>)}</div></DSCard>
    {course&&<><div className="courses-actions"><DSButtonSecondary onClick={save}>Aplicar cambios del curso</DSButtonSecondary><DSButtonSecondary onClick={()=>{if(JSON.stringify(course)===JSON.stringify(data.courses.find(item=>item.id===course.id))||window.confirm('¿Cerrar el curso y descartar los cambios sin aplicar?')){setCourse(null);setRecording(false);}}}>Cerrar edición del curso</DSButtonSecondary>{project&&userId&&<DSButtonSecondary onClick={()=>setRecording(value=>!value)}>{recording?'Cerrar grabación':'Grabar con teleprompter'}</DSButtonSecondary>}</div>
      {recording&&project&&userId&&<Suspense fallback={<p>Cargando teleprompter…</p>}><CourseRecorder userId={userId} project={project} script={lesson?.type==='text'?lesson.content:course.description}/></Suspense>}
      <div className="course-editor">
        <aside className="editor-panel"><h3>Estructura</h3>{course.modules.map((module,index)=><section className="module-item" key={module.id}>
          <DSButtonSecondary aria-pressed={module.id===moduleId} onClick={()=>{setModuleId(module.id);setLessonId(module.lessons[0]?.id??'');}}>{module.title}</DSButtonSecondary>
          {module.id===moduleId&&<><DSInput label="Título del módulo" info="Agrupa las lecciones bajo un nombre que explique lo que aprenderán." value={module.title} onChange={event=>setCourse({...course,modules:course.modules.map(item=>item.id===module.id?{...item,title:event.target.value}:item)})}/>{module.lessons.map(item=><DSButtonSecondary className="lesson-item" aria-pressed={item.id===lessonId} key={item.id} onClick={()=>setLessonId(item.id)}>{item.title}</DSButtonSecondary>)}<DSButtonSecondary onClick={()=>{const next:Lesson={id:crypto.randomUUID(),title:'Nueva lección',type:'text',content:'',durationMinutes:5,question:'',options:['',''],correctOption:0};setCourse({...course,modules:course.modules.map(item=>item.id===module.id?{...item,lessons:[...item.lessons,next]}:item)});setLessonId(next.id);}}>Agregar lección</DSButtonSecondary></>}
          <DSButtonSecondary disabled={index===0} onClick={()=>{const modules=[...course.modules];[modules[index-1],modules[index]]=[modules[index],modules[index-1]];setCourse({...course,modules});}}>Subir módulo</DSButtonSecondary>
        </section>)}<DSButtonSecondary onClick={()=>{const id=crypto.randomUUID();setCourse({...course,modules:[...course.modules,{id,title:`Módulo ${course.modules.length+1}`,lessons:[]}]});setModuleId(id);setLessonId('');}}>Nuevo módulo</DSButtonSecondary></aside>
        <section className="editor-canvas courses-form"><h3>Contenido del curso</h3><DSInput label="Nombre del curso" info="Nombre que identifica tu curso para sus participantes." value={course.name} onChange={event=>setCourse({...course,name:event.target.value})}/><DSTextarea label="Descripción del curso" info="Explica a quién va dirigido y qué aprenderá." value={course.description} onChange={event=>setCourse({...course,description:event.target.value})}/><DSInput label="Precio del curso (S/)" info="Precio del curso en soles; admite dos decimales." type="number" min="0" step="0.01" value={Number.isFinite(course.price) ? course.price : ''} onChange={event=>setCourse({...course,price:event.target.valueAsNumber})}/><ProjectImageField label="Portada del curso" value={course.cover} onChange={value=>setCourse({...course,cover:value})}/>
          {lesson?<fieldset className="courses-form"><legend>Lección seleccionada</legend><DSInput label="Título de lección" info="Describe el tema de esta lección." value={lesson.title} onChange={event=>updateLesson({title:event.target.value})}/><DSSelect label="Tipo de contenido" info="Elige cómo presentar la lección: texto, video, archivo o pregunta de evaluación." value={lesson.type} onChange={event=>updateLesson({type:event.target.value as Lesson['type']})}><option value="text">Texto</option><option value="video">Video</option><option value="file">Archivo</option><option value="quiz">Quiz</option></DSSelect><DSInput label="Duración (minutos)" info="Tiempo estimado para completar esta lección." type="number" min="0" step="1" value={Number.isFinite(lesson.durationMinutes) ? lesson.durationMinutes : ''} onChange={event=>updateLesson({durationMinutes:event.target.valueAsNumber})}/>
            {lesson.type==='text'?<DSTextarea label="Contenido de lección" info="Texto que leerán los participantes en esta lección." value={lesson.content} onChange={event=>updateLesson({content:event.target.value})}/>:lesson.type==='quiz'?<><DSInput label="Pregunta" info="Escribe la pregunta que quieres responder o evaluar." value={lesson.question} onChange={event=>updateLesson({question:event.target.value})}/>{lesson.options.map((option,index)=><DSInput key={index} label={`Opción ${index+1}`} info="Escribe una respuesta posible. Después indica cuál es la correcta." value={option} onChange={event=>updateLesson({options:lesson.options.map((item,i)=>i===index?event.target.value:item)})}/>)}<DSSelect label="Respuesta correcta" info="Selecciona la opción válida de esta pregunta. Revisa que coincida con las opciones escritas." value={lesson.correctOption} onChange={event=>updateLesson({correctOption:Number(event.target.value)})}>{lesson.options.map((_,index)=><option key={index} value={index}>Opción {index+1}</option>)}</DSSelect><DSButtonSecondary onClick={()=>updateLesson({options:[...lesson.options,'']})}>Agregar opción</DSButtonSecondary></>:<DSInput label={lesson.type==='video'?'URL del video':'URL del archivo'} info="Usa un enlace accesible para tus participantes. El editor no sube este recurso al pegar el enlace." type="url" value={lesson.content} onChange={event=>updateLesson({content:event.target.value})}/>}
            <DSButtonSecondary onClick={()=>{if(window.confirm('¿Eliminar esta lección del curso?')){setCourse({...course,modules:course.modules.map(module=>module.id===moduleId?{...module,lessons:module.lessons.filter(item=>item.id!==lessonId)}:module)});setLessonId('');}}}>Eliminar lección</DSButtonSecondary>
          </fieldset>:<p>Elige una lección o crea un módulo para comenzar.</p>}
        </section>
        <aside className="editor-preview"><h3>Vista previa</h3><ProjectImage className="courses-cover" value={course.cover} alt={course.name} /><h3>{course.name}</h3><p>{course.description}</p><p>S/ {Number.isFinite(course.price)?course.price.toFixed(2):'0.00'}</p>{course.modules.map(module=><section key={module.id}><h4>{module.title}</h4><ol>{module.lessons.map(item=><li key={item.id}>{item.title} · {item.durationMinutes} min</li>)}</ol></section>)}{lesson&&<LessonPreview lesson={lesson}/>}</aside>
      </div>
    </>}
  </div>;
}
export function LessonPreview({lesson}:{lesson:Lesson}){return <div className="courses-lesson-preview"><h4>{lesson.title}</h4>{lesson.type==='text'?<p className="courses-text">{lesson.content}</p>:lesson.type==='quiz'?<><p>{lesson.question}</p><ol>{lesson.options.map((option,index)=><li key={index}>{option}</li>)}</ol></>:/^https?:\/\//.test(lesson.content)?lesson.type==='video'?<video controls src={lesson.content} preload="metadata"/>:<a href={lesson.content} target="_blank" rel="noreferrer">Abrir material de la lección</a>:<p>Agrega el recurso de esta lección.</p>}</div>;}
