import { Card as DSCard } from '../../components/ui/DesignSystem';
import { ButtonSecondary as DSButtonSecondary, Input as DSInput } from '../../components/ui/DesignSystem';
import { useModuleDraft } from '../useModuleDraft';
import { useState, type FormEvent } from 'react';
import { useSearchParams } from 'react-router-dom';
import { downloadBlob } from '../../toolkit/api';
import { localDate } from '../dates';
import { certificateSvg, completeLesson, enrollStudent, enrollmentProgress, issueCertificate, recordCoursePayment, type CourseSale, type CoursesData, type Enrollment } from './model';
import { LessonPreview, type CoursesProps } from './CoursesEditor';
import './courses.css';
export default function CoursesDashboard({data,onChange}:CoursesProps){
  const [params,setParams]=useSearchParams();const view=params.get('view')==='sales'?'sales':'students';
  const [student,setStudent]=useState<Omit<Enrollment,'completedLessonIds'|'enrolledAt'>|null>(null);
  const [selected,setSelected]=useState('');const [lessonId,setLessonId]=useState('');const [answer,setAnswer]=useState(-1);
  const [sale,setSale]=useState<CourseSale|null>(null);const [message,setMessage]=useState('');
  useModuleDraft(!!student || !!sale);
  const enrollment=data.enrollments.find(item=>item.id===selected);
  const course=data.courses.find(item=>item.id===enrollment?.courseId);
  const lessons=course?.modules.flatMap(module=>module.lessons)??[];
  const lesson=lessons.find(item=>item.id===lessonId);
  const certificate=data.certificates.find(item=>item.enrollmentId===selected);
  function act(operation:()=>CoursesData,success:string){try{onChange(operation());setMessage(success);return true;}catch(error){setMessage((error as Error).message);return false;}}
  function submit(event:FormEvent,operation:()=>CoursesData,close:()=>void){event.preventDefault();if(act(operation,'Registro actualizado. Guarda el proyecto.'))close();}
  return <div className="courses-module"><h2>Alumnos, progreso y ventas</h2><p role="status">{message}</p>
    <label>Sección del estudio<select value={view} onChange={event=>{const next=new URLSearchParams(params);next.set('view',event.target.value);setParams(next);setMessage('');}}><option value="students">Alumnos y progreso</option><option value="sales">Ventas y cobros</option></select></label>
    <div className="stats-row"><article className="stat-box"><h3>Cursos</h3><strong className="stat-value">{data.courses.length}</strong></article><article className="stat-box"><h3>Inscripciones</h3><strong className="stat-value">{data.enrollments.length}</strong></article><article className="stat-box"><h3>Ingresos registrados</h3><strong className="stat-value">S/ {data.sales.reduce((sum,item)=>sum+item.amount,0).toFixed(2)}</strong></article></div>
    {view==='students'&&<DSCard as="section" className="component-card"><div className="component-header"><h3>Alumnos</h3><DSButtonSecondary disabled={!data.courses.length} onClick={()=>setStudent({id:crypto.randomUUID(),courseId:data.courses[0].id,name:'',email:''})}>Inscribir alumno</DSButtonSecondary></div>
      {!data.courses.length&&<p>Crea un curso desde el editor antes de inscribir alumnos.</p>}
      <div className="courses-table"><table><thead><tr><th>Alumno</th><th>Curso</th><th>Progreso</th><th>Acción</th></tr></thead><tbody>{data.enrollments.map(item=>{const progress=enrollmentProgress(data,item.id);return <tr key={item.id}><td>{item.name}<br/>{item.email}</td><td>{data.courses.find(value=>value.id===item.courseId)?.name}</td><td><progress max={100} value={progress.percent}/><span>{progress.percent}% · {progress.completed}/{progress.total}</span></td><td><DSButtonSecondary onClick={()=>{setSelected(item.id);setLessonId('');setAnswer(-1);}}>Ver progreso de {item.name}</DSButtonSecondary></td></tr>;})}</tbody></table></div>
    </DSCard>}
    {student&&<form className="component-card courses-form" onSubmit={event=>submit(event,()=>enrollStudent(data,student),()=>setStudent(null))}><h3>Inscribir alumno</h3><label>Nombre del alumno<DSInput required value={student.name} onChange={event=>setStudent({...student,name:event.target.value})}/></label><label>Correo del alumno<DSInput type="email" required value={student.email} onChange={event=>setStudent({...student,email:event.target.value})}/></label><label>Curso<select value={student.courseId} onChange={event=>setStudent({...student,courseId:event.target.value})}>{data.courses.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><p>La inscripción no registra un cobro. Anota los pagos recibidos en Ventas.</p><div className="courses-actions"><DSButtonSecondary type="submit">Guardar inscripción</DSButtonSecondary><DSButtonSecondary type="button" onClick={()=>setStudent(null)}>Cancelar inscripción</DSButtonSecondary></div></form>}
    {enrollment&&course&&view==='students'&&<DSCard as="section" className="component-card courses-form"><h3>{enrollment.name} · {course.name}</h3><p>Revisa las lecciones y registra el avance del alumno.</p>
      <label>Lección<select value={lessonId} onChange={event=>{setLessonId(event.target.value);setAnswer(-1);}}><option value="">Selecciona una lección</option>{lessons.map(item=><option value={item.id} key={item.id}>{enrollment.completedLessonIds.includes(item.id)?'✓ ':''}{item.title}</option>)}</select></label>
      {lesson&&<><LessonPreview lesson={lesson}/>{lesson.type==='quiz'&&<fieldset><legend>Respuesta del alumno</legend>{lesson.options.map((option,index)=><label className="courses-check" key={index}><DSInput type="radio" name="quiz-answer" checked={answer===index} onChange={()=>setAnswer(index)}/>{option}</label>)}</fieldset>}<DSButtonSecondary onClick={()=>act(()=>completeLesson(data,enrollment.id,lesson.id,answer),'Lección completada. Guarda el proyecto.')} disabled={enrollment.completedLessonIds.includes(lesson.id)}>{enrollment.completedLessonIds.includes(lesson.id)?'Lección completada':'Registrar lección completada'}</DSButtonSecondary></>}
      {certificate?<DSButtonSecondary onClick={()=>downloadBlob(new Blob([certificateSvg(certificate,data.settings.name)],{type:'image/svg+xml'}),`certificado-${certificate.id}.svg`)}>Descargar certificado</DSButtonSecondary>:<DSButtonSecondary disabled={enrollmentProgress(data,enrollment.id).percent!==100} onClick={()=>act(()=>issueCertificate(data,enrollment.id,crypto.randomUUID()),'Certificado emitido. Guarda el proyecto para conservarlo.')}>Emitir certificado</DSButtonSecondary>}
    </DSCard>}
    {view==='sales'&&<DSCard as="section" className="component-card"><div className="component-header"><h3>Pagos recibidos</h3><DSButtonSecondary disabled={!data.enrollments.length} onClick={()=>setSale({id:crypto.randomUUID(),enrollmentId:data.enrollments[0].id,amount:0,reference:'',date:localDate()})}>Registrar cobro recibido</DSButtonSecondary></div><p>Registra cobros con su referencia. Este formulario no carga tarjetas.</p><div className="courses-table"><table><thead><tr><th>Fecha</th><th>Alumno</th><th>Referencia</th><th>Monto</th></tr></thead><tbody>{data.sales.map(item=><tr key={item.id}><td>{item.date}</td><td>{data.enrollments.find(value=>value.id===item.enrollmentId)?.name}</td><td>{item.reference}</td><td>S/ {item.amount.toFixed(2)}</td></tr>)}</tbody></table></div></DSCard>}
    {sale&&<form className="component-card courses-form" onSubmit={event=>submit(event,()=>recordCoursePayment(data,sale),()=>setSale(null))}><h3>Registrar pago recibido</h3><label>Inscripción<select value={sale.enrollmentId} onChange={event=>setSale({...sale,enrollmentId:event.target.value})}>{data.enrollments.map(item=><option key={item.id} value={item.id}>{item.name} · {data.courses.find(course=>course.id===item.courseId)?.name}</option>)}</select></label><label>Monto recibido (S/)<DSInput type="number" required min="0.01" step="0.01" value={Number.isFinite(sale.amount) ? sale.amount : ''} onChange={event=>setSale({...sale,amount:event.target.valueAsNumber})}/></label><label>Referencia del pago<DSInput required value={sale.reference} onChange={event=>setSale({...sale,reference:event.target.value})}/></label><label>Fecha del pago<DSInput type="date" required value={sale.date} onChange={event=>setSale({...sale,date:event.target.value})}/></label><div className="courses-actions"><DSButtonSecondary type="submit">Guardar cobro</DSButtonSecondary><DSButtonSecondary type="button" onClick={()=>setSale(null)}>Cancelar cobro</DSButtonSecondary></div></form>}
  </div>;
}
