import { useModuleDraft } from '../useModuleDraft';
import { useState, type FormEvent } from 'react';
import { localDate } from '../dates';
import { bookedSeats, cancelTourBooking, reserveTour, saveDeparture, saveGuide, type Departure, type Guide, type TourBooking, type TourismData } from './model';
import type { TourismProps } from './TourismEditor';
import './tourism.css';
export default function TourismDashboard({data,onChange}:TourismProps){
  const [guide,setGuide]=useState<Guide|null>(null);
  const [departure,setDeparture]=useState<Departure|null>(null);
  const [booking,setBooking]=useState<Omit<TourBooking,'status'|'total'>|null>(null);
  const [message,setMessage]=useState('');
  useModuleDraft(!!guide || !!departure || !!booking);
  function act(event:FormEvent, operation:()=>TourismData, close:()=>void){event.preventDefault();try{onChange(operation());close();setMessage('Cambio registrado. Guarda el proyecto.');}catch(error){setMessage((error as Error).message);}}
  return <div className="tourism-module"><h2>Salidas, guías y reservas</h2><p role="status">{message}</p>
    <section className="tour-card"><div className="tour-header"><h3>Guías</h3><button onClick={()=>setGuide({id:crypto.randomUUID(),name:'',contact:'',languages:''})}>Agregar guía</button></div><div className="tour-grid">{data.guides.map(item=><article className="tour-item" key={item.id}><h3>{item.name}</h3><p>{item.contact}</p><p>{item.languages}</p><button onClick={()=>setGuide({...item})}>Editar guía {item.name}</button></article>)}</div></section>
    {guide&&<form className="tour-card tour-form" onSubmit={event=>act(event,()=>saveGuide(data,guide),()=>setGuide(null))}><h3>Datos del guía</h3><label>Nombre del guía<input required value={guide.name} onChange={event=>setGuide({...guide,name:event.target.value})}/></label><label>Contacto del guía<input value={guide.contact} onChange={event=>setGuide({...guide,contact:event.target.value})}/></label><label>Idiomas<input value={guide.languages} onChange={event=>setGuide({...guide,languages:event.target.value})}/></label><div className="tour-actions"><button type="submit">Guardar guía</button><button type="button" onClick={()=>setGuide(null)}>Cancelar guía</button></div></form>}
    <section className="tour-card"><div className="tour-header"><h3>Salidas por fecha</h3><button disabled={!data.tours.length||!data.guides.length} onClick={()=>setDeparture({id:crypto.randomUUID(),tourId:data.tours[0].id,guideId:data.guides[0].id,date:localDate(),time:'09:00',capacity:10})}>Programar salida</button></div>{(!data.tours.length||!data.guides.length)&&<p>Primero crea una experiencia y agrega un guía.</p>}
      <div className="tour-grid">{[...data.departures].sort((a,b)=>`${a.date} ${a.time}`.localeCompare(`${b.date} ${b.time}`)).map(item=><article className="tour-item" key={item.id}><h3>{data.tours.find(tour=>tour.id===item.tourId)?.name}</h3><p>{item.date} · {item.time}</p><p>Guía: {data.guides.find(value=>value.id===item.guideId)?.name}</p><p>{item.capacity-bookedSeats(data,item.id)} de {item.capacity} plazas disponibles</p><div className="tour-actions"><button disabled={item.capacity<=bookedSeats(data,item.id)} onClick={()=>setBooking({id:crypto.randomUUID(),departureId:item.id,customer:'',contact:'',people:1})}>Reservar {item.date} {item.time}</button><button onClick={()=>setDeparture({...item})}>Editar salida</button></div></article>)}</div>
    </section>
    {departure&&<form className="tour-card tour-form" onSubmit={event=>act(event,()=>saveDeparture(data,departure),()=>setDeparture(null))}><h3>Programar salida</h3><label>Experiencia<select value={departure.tourId} onChange={event=>setDeparture({...departure,tourId:event.target.value})}>{data.tours.map(tour=><option key={tour.id} value={tour.id}>{tour.name}</option>)}</select></label><label>Guía asignado<select value={departure.guideId} onChange={event=>setDeparture({...departure,guideId:event.target.value})}>{data.guides.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Fecha de salida<input type="date" required value={departure.date} onChange={event=>setDeparture({...departure,date:event.target.value})}/></label><label>Hora local de salida<input type="time" required value={departure.time} onChange={event=>setDeparture({...departure,time:event.target.value})}/></label><label>Capacidad de la salida<input type="number" required min="1" step="1" value={Number.isFinite(departure.capacity) ? departure.capacity : ''} onChange={event=>setDeparture({...departure,capacity:event.target.valueAsNumber})}/></label><div className="tour-actions"><button type="submit">Guardar salida</button><button type="button" onClick={()=>setDeparture(null)}>Cancelar salida</button></div></form>}
    {booking&&<form className="tour-card tour-form" onSubmit={event=>act(event,()=>reserveTour(data,booking),()=>setBooking(null))}><h3>Reserva de experiencia</h3><label>Nombre del viajero<input required value={booking.customer} onChange={event=>setBooking({...booking,customer:event.target.value})}/></label><label>Contacto del viajero<input required value={booking.contact} onChange={event=>setBooking({...booking,contact:event.target.value})}/></label><label>Personas<input type="number" required min="1" step="1" value={Number.isFinite(booking.people) ? booking.people : ''} onChange={event=>setBooking({...booking,people:event.target.valueAsNumber})}/></label><p>La reserva asegura plazas; no registra un cobro.</p><div className="tour-actions"><button type="submit">Confirmar reserva</button><button type="button" onClick={()=>setBooking(null)}>Cerrar reserva</button></div></form>}
    <section className="tour-card"><h3>Reservas registradas</h3>{data.bookings.map(item=><article className="tour-booking" key={item.id}><h3>{item.customer}</h3><p>{item.contact} · {item.people} personas · S/ {item.total.toFixed(2)}</p><p>{data.departures.find(value=>value.id===item.departureId)?.date} · {item.status==='confirmed'?'Confirmada':'Cancelada'}</p>{item.status==='confirmed'&&<button onClick={()=>{if(window.confirm('¿Cancelar la reserva y liberar las plazas?'))onChange(cancelTourBooking(data,item.id));}}>Cancelar reserva de {item.customer}</button>}</article>)}</section>
  </div>;
}
