import { Card as DSCard } from '../../components/ui/DesignSystem';
import { Input as DSInput, Textarea as DSTextarea, ButtonSecondary as DSButtonSecondary } from '../../components/ui/DesignSystem';
import { tourTimeZones } from './tourismPublicationModel';
import ProjectImage from '../../components/shared/ProjectImage';
import ProjectImageField from '../../components/shared/ProjectImageField';
import { useModuleDraft } from '../useModuleDraft';
import { useState, type FormEvent } from 'react';
import { saveTour, tourMapUrl, type Tour, type TourismData } from './model';
import './tourism.css';
export type TourismProps = { data: TourismData; onChange: (data: TourismData) => void };
export default function TourismEditor({ data, onChange }: TourismProps) {
  const [tour, setTour] = useState<Tour | null>(null);
  const [message, setMessage] = useState('');
  useModuleDraft(!!tour);
  function submit(event: FormEvent) { event.preventDefault(); if (!tour) return; try { onChange(saveTour(data, tour)); setTour(null); setMessage('Experiencia actualizada. Guarda el proyecto.'); } catch (error) { setMessage((error as Error).message); } }
  return <div className="tourism-module"><h2>Experiencias e itinerarios</h2><p role="status">{message}</p>
    <DSCard as="section" className="tour-card tour-form"><h3>Tu agencia</h3><label>Zona horaria de las salidas<select disabled={data.bookings.length>0} value={data.settings.timeZone??'America/Lima'} onChange={event=>onChange({...data,settings:{...data.settings,timeZone:event.target.value}})}>{tourTimeZones.map(zone=><option key={zone} value={zone}>{zone.replaceAll('_',' ')}</option>)}</select></label>{data.bookings.length>0&&<p>Se conserva la zona horaria de las reservas existentes.</p>}{([['name','Nombre de agencia'],['whatsapp','WhatsApp']] as const).map(([key,label])=><label key={key}>{label}<DSInput value={data.settings[key]} onChange={event=>onChange({...data,settings:{...data.settings,[key]:event.target.value}})} /></label>)}<label>Sobre la agencia<DSTextarea value={data.settings.about} onChange={event=>onChange({...data,settings:{...data.settings,about:event.target.value}})} /></label></DSCard>
    <DSCard as="section" className="tour-card"><div className="tour-header"><h3>Tus tours</h3><DSButtonSecondary onClick={()=>setTour({id:crypto.randomUUID(),name:'',description:'',price:0,durationMinutes:60,image:'',active:true,itinerary:[],meetingPoint:'',latitude:0,longitude:0})}>Nueva experiencia</DSButtonSecondary></div>
      <div className="tour-grid">{data.tours.map(item=><article className="tour-item" key={item.id}><ProjectImage value={item.image} alt={item.name} /><h3>{item.name}</h3><p>{item.description}</p><p>{item.durationMinutes} minutos · S/ {item.price.toFixed(2)} por persona</p><ol>{item.itinerary.map(stop=><li key={stop.id}><strong>{stop.title}</strong><p>{stop.description}</p></li>)}</ol><p>Punto de encuentro: {item.meetingPoint}</p><a target="_blank" rel="noreferrer" href={tourMapUrl(item)}>Ver punto en el mapa</a><p>{item.active?'Experiencia activa':'Experiencia oculta'}</p><DSButtonSecondary onClick={()=>setTour(structuredClone(item))}>Editar {item.name}</DSButtonSecondary></article>)}</div>
      {!data.tours.length&&<p>Crea una experiencia con su recorrido y punto de encuentro.</p>}
    </DSCard>
    {tour&&<form className="tour-card tour-form" onSubmit={submit}><h3>Editar experiencia</h3>
      <label>Nombre de experiencia<DSInput required value={tour.name} onChange={event=>setTour({...tour,name:event.target.value})}/></label><label>Descripción<DSTextarea value={tour.description} onChange={event=>setTour({...tour,description:event.target.value})}/></label>
      <label>Precio por persona (S/)<DSInput type="number" required min="0" step="0.01" value={Number.isFinite(tour.price) ? tour.price : ''} onChange={event=>setTour({...tour,price:event.target.valueAsNumber})}/></label><label>Duración en minutos<DSInput type="number" required min="1" step="1" value={Number.isFinite(tour.durationMinutes) ? tour.durationMinutes : ''} onChange={event=>setTour({...tour,durationMinutes:event.target.valueAsNumber})}/></label>
      <ProjectImageField label="Imagen de la experiencia" value={tour.image} onChange={value=>setTour({...tour,image:value})}/><label>Punto de encuentro<DSInput required value={tour.meetingPoint} onChange={event=>setTour({...tour,meetingPoint:event.target.value})}/></label>
      <div className="tour-grid"><label>Latitud<DSInput type="number" required min="-90" max="90" step="any" value={Number.isFinite(tour.latitude) ? tour.latitude : ''} onChange={event=>setTour({...tour,latitude:event.target.valueAsNumber})}/></label><label>Longitud<DSInput type="number" required min="-180" max="180" step="any" value={Number.isFinite(tour.longitude) ? tour.longitude : ''} onChange={event=>setTour({...tour,longitude:event.target.valueAsNumber})}/></label></div>
      <fieldset><legend>Itinerario</legend>{tour.itinerary.map((stop,index)=><div className="tour-form tour-stop" key={stop.id}><label>Parada {index+1}<DSInput required value={stop.title} onChange={event=>setTour({...tour,itinerary:tour.itinerary.map(item=>item.id===stop.id?{...item,title:event.target.value}:item)})}/></label><label>Detalle de parada<DSTextarea value={stop.description} onChange={event=>setTour({...tour,itinerary:tour.itinerary.map(item=>item.id===stop.id?{...item,description:event.target.value}:item)})}/></label><div className="tour-actions"><DSButtonSecondary type="button" disabled={index===0} onClick={()=>{const itinerary=[...tour.itinerary];[itinerary[index-1],itinerary[index]]=[itinerary[index],itinerary[index-1]];setTour({...tour,itinerary});}}>Subir parada {index+1}</DSButtonSecondary><DSButtonSecondary type="button" onClick={()=>setTour({...tour,itinerary:tour.itinerary.filter(item=>item.id!==stop.id)})}>Quitar parada {index+1}</DSButtonSecondary></div></div>)}<DSButtonSecondary type="button" onClick={()=>setTour({...tour,itinerary:[...tour.itinerary,{id:crypto.randomUUID(),title:'',description:''}]})}>Agregar parada</DSButtonSecondary></fieldset>
      <label className="tour-check"><DSInput type="checkbox" checked={tour.active} onChange={event=>setTour({...tour,active:event.target.checked})}/>Aceptar reservas para esta experiencia</label><div className="tour-actions"><DSButtonSecondary type="submit">Guardar experiencia</DSButtonSecondary><DSButtonSecondary type="button" onClick={()=>setTour(null)}>Cancelar</DSButtonSecondary></div>
    </form>}
  </div>;
}
