import test from 'node:test';
import assert from 'node:assert/strict';
import { detectState, prioritizeTasks, learnPatterns, detectSilences, keptSegments, moveItem, safeHttps, localDate } from '../src/toolkit/engine.ts';

const metrics = { lastActionTime: 1_000_000, completionRate: 0, helpClicks: [], skipped: 0, fastTasks: 0, scrollDepth: 0, mouseMovement: 0, timeOnTask: 0 };
test('exhausted requires more than 15 seconds and less than 30% completion', () => { assert.equal(detectState(metrics, 1_015_000), 'focused'); assert.equal(detectState(metrics, 1_015_001), 'exhausted'); assert.equal(detectState({...metrics,completionRate:0.3},1_015_001),'focused'); });
test('help uses a rolling 60-second window after an action', () => { assert.equal(detectState({ ...metrics, lastActionTime:2_000_000, helpClicks: [1_950_000, 1_970_000, 1_980_000] }, 2_000_000), 'anxious'); assert.equal(detectState({ ...metrics, lastActionTime: 2_000_000, helpClicks: [1_000_000, 1_970_000, 1_980_000] }, 2_000_000), 'focused'); });
test('all focus states are reachable and focused is the default', () => { assert.equal(detectState({ ...metrics, skipped: 2 }, 1_000_000), 'low-motivation'); assert.equal(detectState({ ...metrics, fastTasks: 3 }, 1_000_000), 'high-energy'); assert.equal(detectState({ ...metrics, scrollDepth: 81, mouseMovement: 4 }, 1_000_000), 'confused'); });
const task = (id, patch = {}) => ({ id, title: id, minutes: 15, impact: 'ventas', progress: 0, dependencies: [], done: false, priority: 0, ...patch });
test('unmet, missing and cyclic dependencies cannot be suggested', () => { const tasks = [task('offer'), task('sell', { priority: 99, dependencies: ['offer'] }), task('missing', { dependencies: ['unknown'] }), task('cycle', { dependencies: ['cycle'] })]; assert.deepEqual(prioritizeTasks(tasks, 'ventas', 'focused').map(t => t.id), ['offer']); assert.equal(prioritizeTasks([{ ...tasks[0], done: true }, tasks[1]], 'ventas', 'focused')[0].id, 'sell'); });
test('unfinished work is favored and the source array is never mutated', () => { const tasks = [task('new'), task('started', { progress: 50 })]; const before = JSON.stringify(tasks); assert.equal(prioritizeTasks(tasks, 'ventas', 'focused')[0].id, 'started'); assert.equal(JSON.stringify(tasks), before); });
test('short tasks fit a smaller focus window', () => { assert.equal(prioritizeTasks([task('long', { minutes: 30 }), task('short', { minutes: 3 })], 'ventas', 'exhausted')[0].id, 'short'); });
test('learning has an honest empty state and excludes help and incomplete tasks', () => { assert.equal(learnPatterns([]).preferredHour, null); const a = { id: 'a', at: new Date(2026, 8, 23, 10).getTime(), completed: true, duration: 30, type: 'video' }; const p = learnPatterns([a, { ...a, id: 'b', duration: 60 }, { ...a, id: 'c', type: 'help' }, { ...a, id: 'd', completed: false, type: 'landing' }]); assert.equal(p.sampleSize, 2); assert.equal(p.averageSeconds, 45); assert.equal(p.preferredHour, 10); assert.deepEqual(p.dropoffTypes, ['landing']); });
test('silence detection retains short pauses and examines both channels', () => { const quiet = new Float32Array(2000); const audible = new Float32Array(2000).fill(.2); assert.deepEqual(detectSilences([quiet], 1000), [{ start: 0, end: 2 }]); assert.deepEqual(detectSilences([quiet, audible], 1000), []); const mixed = new Float32Array(2000).fill(.2); mixed.fill(0, 500, 1000); assert.deepEqual(detectSilences([mixed], 1000), []); mixed.fill(0, 500, 1500); assert.deepEqual(detectSilences([mixed], 1000), [{ start: .5, end: 1.5 }]); });
test('cuts preserve speech padding, handle overlapping and unsorted ranges', () => { assert.deepEqual(keptSegments(10, [{ start: 6, end: 8 }, { start: 2, end: 4 }], .1), [{ start: 0, end: 2.1 }, { start: 3.9, end: 6.1 }, { start: 7.9, end: 10 }]); assert.deepEqual(keptSegments(10, [{ start: 1, end: 5 }, { start: 2, end: 6 }], 0), [{ start: 0, end: 1 }, { start: 6, end: 10 }]); assert.deepEqual(keptSegments(0, []), []); });
test('timeline moves preserve every item and ignore invalid indices', () => { const source = ['a', 'b', 'c']; assert.deepEqual(moveItem(source, 0, 2), ['b', 'c', 'a']); assert.deepEqual(source, ['a', 'b', 'c']); assert.deepEqual(moveItem(source, -1, 2), source); });
test('public CTA URLs reject scripts and lookalike hosts', () => { assert.equal(safeHttps('javascript:alert(1)'), ''); assert.equal(safeHttps('http://calendly.com/test', 'calendly.com'), ''); assert.equal(safeHttps('https://calendly.com.evil.test/test', 'calendly.com'), ''); assert.equal(safeHttps('https://calendly.com/test', 'calendly.com'), 'https://calendly.com/test'); });
test('calendar dates preserve the local day', () => { assert.equal(localDate(new Date(2026, 8, 23, 23, 59)), '2026-09-23'); });
test('confused requires deep scrolling and fewer than five pointer movements',()=>{
 assert.equal(detectState({...metrics,scrollDepth:80,mouseMovement:0},1_000_000),'focused');
 assert.equal(detectState({...metrics,scrollDepth:90,mouseMovement:5},1_000_000),'focused');
});
